### ISSUE TITLE
Icon is undefined

### ISSUE THREAD

**Issue by GuillouTran** [telmogoncalves/telmo#14]
Hi Telmo,

Recently, I keep getting this "simple" error but I just can't find what caused them. So the error is "TypeError: can't access property "hex", icon is undefined" caused by the /component/icon.js file. The code and configuration are identical from your repo and the error log is:

``` 1 of 1 unhandled error
Unhandled Runtime Error

TypeError: can't access property "hex", icon is undefined
Source

components/Icon.js (11:8) @ Icon

   9 | data-icon={type}
  10 | style={{
> 11 |   fill: `#${icon.hex}`,
     |  ^
  12 |   display: 'inline-block',
  13 |   width: '50px',
  14 |   margin: '0 auto',
```

It's very strange because I could simple remove the icon related line and the app would work just fine(without the icon of course) so i think the app is probably broke because of the package or some miss config somewhere caus ed by me?

By the way, I am @guilloutran!

**Comment by telmogoncalves** [comment]
What's the icon you're trying to render?

**Comment by GuillouTran** [comment]
@telmogoncalves, sorry for the late response,

I was trying to render those icon you set in the "uses" pages and this error keep pop up

**Comment by telmogoncalves** [comment]
If you want create a repo with your code and I'll take a look.

**Comment by GuillouTran** [comment]
I already did. 
https://github.com/guilloutran/guilloutran.com

**Comment by telmogoncalves** [comment]
Alright, the problem here is that the `simple-icons` library got updated on your project. The following icons should change:

`Zeit` → `Vercel`
`Rails` → `Ruby on Rails`

**Comment by GuillouTran** [comment]
Ah. I see! I haven’t realized that detail because the CI and local test passed. Thanks
