### ISSUE TITLE
Any Plan for Hacktoberfest ?

### ISSUE THREAD

**Issue by shaonkabir8** [telmogoncalves/telmo#16]
Hi 👋
Any Plans for #hacktoberfest ?
we'll make something better together. 🚀
Thanks

**Comment by h1eutran** [comment]
He doesn’t seem to active recently I think

**Comment by shaonkabir8** [comment]
> He doesn’t seem to active recently I think

Yep 👍 . October is almost come to the end and surely closing the Hacktoberfest soon.  
I gonna close this issue 😥 

But it's much more important to keep our `open source` contribution going. 🚀 

I just love be introduce mine as an `Open Source Enthusiast` ❤️ 
@GuillouTran 
Happy Contributing [mate](@GuillouTran) 👊

**Comment by shaonkabir8** [comment]
> He doesn’t seem to active recently I think

Yep 👍 . October is almost come to the end and surely closing the Hacktoberfest soon.  
I gonna close this issue 😥 

But it's much more important to keep our `open source` contribution going. 🚀 

I just love be introduce mine as an `Open Source Enthusiast` ❤️ 

Happy Contributing [mate](https://github.com/GuillouTran) 👊

**Comment by h1eutran** [comment]
I mean, there’s plenty of projects out there! Hope you’ll found one that suite yourself best!
