### ISSUE TITLE
adding meta data

### ISSUE THREAD

**Issue by JosiasAurel** [telmogoncalves/telmo#4]
hello dear. thanks for making this awesome stuff - dnating your blog for free; But i have this issue. i encounter problems adding meta data to a blog post. idk if i am wrong but i tried the code below but when i inpect in chrome dev tools, i dont see anything.  Help appreciated please

```
---
title: "Welcome To My Blog"
date: "2020-05-20"
og:
  description: "You are welcomed"
  image: "url-to-image"
author:
  twitter: "jondoe"
  name: "John Doe"
monetizations: "api key"
---

Markdown

---
Nice
---

Cool
```

**Comment by JosiasAurel** [comment]
the issue is at the leve of monetizations

**Comment by telmogoncalves** [comment]
If you refer to [this file](https://github.com/telmogoncalves/telmo/blob/master/pages/writings/%5Bslug%5D.js#L13), that's where it's reading the data.

You would need to do something like:

```js
const { title, author, monetizations } = frontmatter
```

and use `monetizations` whatever you want in the page.

**Comment by JosiasAurel** [comment]
Ok thanks. That gives me ability to also add any other metadata like social preview and such . Understood 🙏
