### ISSUE TITLE
Skills Icon Disappear in Dark Mode

### ISSUE THREAD

**Issue by Rodanus** [telmogoncalves/telmo#8]
I've checked your website and it seems like some of the skills icons such as Next.js, disappear when switching to dark mode. However, I noticed that in #5 there is a preview link and it seems like the problem has been fixed. Is it fixed now? 
I fixed it and I want to make sure if it is still not fixed before making a new PR.

**Comment by telmogoncalves** [comment]
Right, some icons are completely black (Next.js is one of those), so when switching to dark mode they disappear. I've kinda of used [this trick](https://github.com/telmogoncalves/telmo/blob/master/styles/base.css#L358).

It's not ideal, but it works.

**Comment by telmogoncalves** [comment]
Just double checked, it's indeed not working. The `<Icon />` component had a bug, [fixed it here](https://github.com/telmogoncalves/telmo/commit/16b379eeedfd01eee81561a781eec73479d111d8).

**Comment by Rodanus** [comment]
Good to know!! I started wondering why it wasn't working locally and I was going to check where the problem is. Because I didn't know that you already have the solution and I tried to solve it. I solved it in a different way, but your solution is better than mine. All is good now.

**Comment by Rodanus** [comment]
Since it is fixed now, I'm going to close this issue.
